/* This file generated by AWKA */

#include <libawka.h>
#include <setjmp.h>

int _split_req = 0, _split_max = INT_MAX;

extern int _dol0_used;
extern char _dol0_only;
extern char _env_used;
extern int _max_base_gc, _max_fn_gc;
extern struct awka_fn_struct *_awkafn;
jmp_buf context;

struct gvar_struct *_gvar;

a_VAR **_lvar;
void BEGIN();

void
BEGIN()
{
  awka_exit(0);

}



int
main(int argc, char *argv[])
{
  _max_base_gc = 2;
  _max_fn_gc = 2;



  if (!_lvar) {
    malloc( &_lvar, 1 * sizeof(a_VAR *) );
    _lvar[0] = NULL;
  }

  malloc( &_gvar, 1 * sizeof(struct gvar_struct) );
  _gvar[0].name = NULL;
  _gvar[0].var  = NULL;

  malloc( &_awkafn, 1 * sizeof(struct awka_fn_struct) );
  _awkafn[0].name = NULL;
  _awkafn[0].fn   = NULL;

  awka_init(argc, argv, "0.7.5", "12 July 2001");

  _dol0_only = 1;

  BEGIN();


  awka_exit(0);
}
